[theme]
primaryColor = "#008080"              # Teal
backgroundColor = "#f7fdfd"           # Very light teal-tinted white
secondaryBackgroundColor = "#e0f7f7"  # Soft mint background for cards, etc.
textColor = "#083d3d"                 # Deep teal for readability
font = "sans serif"                   # Clean and modern